# EDA - Other Datasets



## Dataset

The dataset is available at [KuaiRec](https://nas.chongminggao.top:4430/datasets/KuaiRec.zip).

We can download the dataset via a wget command:

In [1]:
%%bash
if [ ! -d "../data_final_project" ]; then
  wget --no-check-certificate 'https://drive.usercontent.google.com/download?id=1qe5hOSBxzIuxBb1G_Ih5X-O65QElollE&export=download&confirm=t&uuid=b2002093-cc6e-4bd5-be47-9603f0b33470' -O KuaiRec.zip
  unzip KuaiRec.zip -d ../data_final_project
else
  echo "Directory '../data_final_project' already exists. Skipping download."
fi

Directory '../data_final_project' already exists. Skipping download.

## Preprocessing

In [9]:
# Import libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# set plot size
plt.rcParams["figure.figsize"] = (20, 13)
%matplotlib inline
%config InlineBackend.figure_format = "retina"

In [10]:
interactions = pd.read_csv("../data_final_project/KuaiRec/data/small_matrix.csv")
user_social = pd.read_csv("../data_final_project/KuaiRec/data/social_network.csv")
user_features = pd.read_csv("../data_final_project/KuaiRec/data/user_features.csv")
item_features = pd.read_csv("../data_final_project/KuaiRec/data/item_daily_features.csv")
item_categories = pd.read_csv("../data_final_project/KuaiRec/data/item_categories.csv")
captions = pd.read_csv("../data_final_project/KuaiRec/data/kuairec_caption_category.csv", lineterminator='\n')

In [11]:
len(item_features.columns)

58

# User

In [4]:
display(user_social.head())
user_features.columns = user_features.columns.str.strip()


for i in range(0, 18):
    user_features.drop(columns=[f"onehot_feat{i}"],  inplace=True, errors="ignore")
display(user_features.head())

   user_id friend_list
0     3371      [2975]
1       24      [2665]
2     4402        [38]
3     4295      [4694]
4     7087      [7117]

,user_id,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,friend_user_num_range,register_days,register_days_range
0,0,high_active,0,0,0,5,"(0,10]",0,0,0,0,107,61-90
1,1,full_active,0,0,0,386,"(250,500]",4,"[1,10)",2,"[1,5)",327,181-365
2,2,full_active,0,0,0,27,"(10,50]",0,0,0,0,116,91-180
3,3,full_active,0,0,0,16,"(10,50]",0,0,0,0,105,61-90
4,4,full_active,0,0,0,122,"(100,150]",4,"[1,10)",0,0,225,181-365

## Items

In [5]:
display(item_features.head())
display(item_categories.head())

,video_id,date,author_id,video_type,upload_dt,upload_type,visible_status,video_duration,video_width,video_height,...,download_cnt,download_user_num,report_cnt,report_user_num,reduce_similar_cnt,reduce_similar_user_num,collect_cnt,collect_user_num,cancel_collect_cnt,cancel_collect_user_num
0,0,20200705,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,...,8,8,0,0,3,3,NaN,NaN,NaN,NaN
1,0,20200706,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,...,2,2,0,0,5,5,NaN,NaN,NaN,NaN
2,0,20200707,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,...,2,2,0,0,0,0,NaN,NaN,NaN,NaN
3,0,20200708,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,...,3,3,0,0,3,3,NaN,NaN,NaN,NaN
4,0,20200709,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,...,2,2,2,1,1,1,NaN,NaN,NaN,NaN

   video_id     feat
0         0      [8]
1         1  [27, 9]
2         2      [9]
3         3     [26]
4         4      [5]

In [6]:
merged_item_data = item_features.merge(item_categories, on='video_id', how='left')

In [7]:
display(merged_item_data["upload_type"].unique())

array(['ShortImport', 'PictureSet', 'Kmovie', 'ShortCamera', 'LongImport',
       'LongCamera', 'FollowShoot', 'LongPicture', 'Web', 'UNKNOWN',
       'FlashPhoto', 'AiCutVideo', 'ShareFromOtherApp', 'PhotoCopy',
       'LocalCollection', 'SameFrame', 'PictureCopy',
       'LocalIntelligenceAlbum'], dtype=object)

Now that you saw all the preprocessing options and analysis over the datasets you can either :
- [Go back to the EDA](./EDA.ipynb)
- [Go back to the main notebook](../FinalProject_Notebook.ipynb)